version: "3"
services:
  jisdlab:
    build: ./
    restart: always
    image: jisdlab
    command: "jupyter lab --allow-root"
    container_name: JISDLab
    ports:
      - 21510:21510
      - 39876:39876
    volumes:
      - ./JISD:/JISDLab/JISD
      - ./IJava:/JISDLab/IJava
      - ./debugspace:/workspaces/debugspace
      - ./sample:/workspaces/sample
    working_dir: /workspaces
    extra_hosts:
      - host.docker.internal:host-gateway
### If you use JISDVis, please remove the comment out below
#    networks:
#      - jisdlab-network
#networks:
#  jisdlab-network:
#    external: true
